# Generated by Django 5.1.5 on 2025-01-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250123_2039'),
    ]

    operations = [
    ]
