# Generated by Django 5.1.5 on 2025-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_balance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_spin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
