# Generated by Django 5.1.5 on 2025-01-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_spinrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpinRecord',
        ),
    ]
