# Generated by Django 5.2 on 2025-04-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blackjackgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('in_game', 'In-Game')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('win', 'Win'), ('purchase', 'Purchase'), ('loss', 'Loss'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='win', max_length=10),
        ),
    ]
